import "./globals.css";

import Footer from "./components/Footer";
import Header from "./components/Header";
import { Inter } from "next/font/google";
import { fetchLayoutSections } from "@/api/functions";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const res = await fetchLayoutSections();

  const { headerSection, footerSection } = res.data;

  const header = headerSection.header;
  const footer = footerSection.footer;

  return (
    <html lang="el" data-theme="light">
      <body className={inter.className}>
        <Header header={header} />
        <main>{children}</main>
        <Footer footer={footer} />
      </body>
    </html>
  );
}
